"
" Vim
"

set nocompatible

"
" Plugins
"

filetype plugin indent on

"
" Leader
"

let mapleader=","
let g:mapleader=","

"
" Settings
"

" no beeps
set noerrorbells

" split vertical window right to the current windows
set splitright

" split horizontal windows below to the current window
set splitbelow

" set default encoding to UTF-8
set encoding=utf-8

" automatically save before :next, :make etc
set autowrite

" automatically reread changed files without asking me anything
set autoread

"
" Search
"

" search as characters are entered
set incsearch

" highlight matches
set hlsearch

" ignore case when searching
set ignorecase

" turn off search hightlight
nnoremap <leader><space> :nohlsearch<CR>

"
" Backup & swap
"

set noswapfile
set nobackup

"
" Ui
"

" dont't wrap lines
set nowrap

" show line numbers
set number

" show command in bottom bar
set showcmd

" show the mode in bottom bar
set showmode

" don't hightlight matching [{()}]
set noshowmatch

" redraw only when we need to
set lazyredraw

set nocursorcolumn
set nocursorline

"
" Colors
"

" enable syntax processing
syntax enable

" use vim-colors-xcode
colorscheme xcodelight

"
" Ruler
"

set colorcolumn=80
highlight ColorColumn ctermbg=DarkGray

"
" Spaces & tabs
"

" number of visual spaces per TAB
set tabstop=2

" number of spaces in tab when editing
set softtabstop=2

" number of spaces for step
set shiftwidth=2

" tabs are spaces
set expandtab

" automatically remove all trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e

"
" Dart
"

let dart_html_in_string=v:true
let g:dart_style_guide=2
let g:dart_format_on_save=1

"
" Syntax highlight
"

let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
" let g:go_highlight_operators = 1
" let g:go_highlight_extra_types = 1
" let g:go_highlight_build_constraints = 1
" let g:go_highlight_generate_tags = 1
